apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-client
data:
  # logging
  # LOG_ENCODING: json

  # monitoring
  ENABLE_MONITORING: "false"
  # ENABLE_CUSTOM_METRICS: "true"

  # tracing
  ENABLE_TRACING: "false"
  # JAEGER_SERVICE_NAME: grpc-client
  # JAEGER_SAMPLER_TYPE: const
  # JAEGER_SAMPLER_PARAM: "1"
  # JAEGER_REPORTER_FLUSH_INTERVAL: 1s
  # JAEGER_AGENT_PORT: "6831"
  # JAEGER_AGENT_HOST: jaeger-agent.tracing.svc.cluster.local
  # JAEGER_REPORTER_LOG_SPANS: "true"

  # grpc
  GRPC_SERVER_ADDRESS: grpc-server.apps.svc.cluster.local:50051
  GRPC_GREETING_NAME: WorkshopTage21
