apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer
data:
  # logging
  # LOG_ENCODING: json

  # monitoring
  ENABLE_MONITORING: "false"
  # ENABLE_CUSTOM_METRICS: "true"

  # tracing
  ENABLE_TRACING: "false"
  # JAEGER_SERVICE_NAME: kafka-producer
  # JAEGER_SAMPLER_TYPE: const
  # JAEGER_SAMPLER_PARAM: "1"
  # JAEGER_REPORTER_FLUSH_INTERVAL: 1s
  # JAEGER_AGENT_PORT: "6831"
  # JAEGER_AGENT_HOST: jaeger-agent.tracing.svc.cluster.local
  # JAEGER_REPORTER_LOG_SPANS: "true"

  # kafka
  KAFKA_BOOTSTRAP_SERVERS: strimzi-kafka-bootstrap.apps.svc.cluster.local
  KAFKA_PORT: "9092"
  KAFKA_TOPIC: my-topic
