apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-consumer
data:
  # logging
  LOG_ENCODING: json

  # tracing
  JAEGER_SERVICE_NAME: kafka-consumer
  JAEGER_SAMPLER_TYPE: const
  JAEGER_SAMPLER_PARAM: "1"
  JAEGER_REPORTER_LOG_SPANS: "true"
  JAEGER_REPORTER_FLUSH_INTERVAL: 1s
  JAEGER_AGENT_PORT: "6831"
  JAEGER_AGENT_HOST: jaeger-agent.tracing.svc.cluster.local

  # kafka
  KAFKA_BOOTSTRAP_SERVERS: strimzi-kafka-bootstrap.kafka.svc.cluster.local
  KAFKA_PORT: "9092"
  KAFKA_TOPIC: my-topic
  KAFKA_CONSUMER_GROUP: my-group
  KAFKA_AUTO_OFFSET_RESET: latest
